repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.11.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate_no_variables
#    - id: terraform_docs
- repo: https://github.com/detailyang/pre-commit-shell
  rev: 1.0.5
  hooks:
    - id: shell-lint
